### ISSUE TITLE
Secure admin page

### ISSUE THREAD

**Issue by michaelyfan** [dscgt/recycling_checkin#11]
A normal crewmember shouldn't be able to access the admin page. Assuming:

- the checkout app will be on a single, immobile device
- both crewmembers and department administrators will have access to the device
- the app is meant to function for extended periods of time without internet connection

What is the best way to secure the administrator page? Will a simple clientside password suffice, since the app will only be installed on one device?

**Comment by michaelyfan** [comment]
What do you guys think of this, @JackWolfard @tujson ? I currently have a completely clientside "authentication" login screen, using a password that's hashed before being stored locally (shared_preferences). This may be sufficient or the only option given the constraints of the device (see above).

**Comment by tujson** [comment]
Is there a reason why we can't use Firebase Authentication and store user roles in a table?

As for offline, the user role could be stored offline after initial sign in.

**Comment by michaelyfan** [comment]
We've no need to store user roles--only admins need to login.
How would Firebase Authentication work offline? From my research it doesn't have that capability.

**Comment by tujson** [comment]
If a user has logged in before, store their role.
When the app starts and there is no internet connection, look for a stored role. If there isn't a stored role, ask the user to log in when there's an internet connection. If there is a stored role, assume that role.

**Comment by tujson** [comment]
Oh, if only admins have this role, it might be too much to add Firebase Auth and all this just for admin roles.

I don't necessarily like the idea of having the admin role be behind a password. I guess it's fine since devices are known and "secure". Having different flavors for regular users and admins might be the optimal approach.

**Comment by michaelyfan** [comment]
Ideally, admins need to be able to "login"--enter a password to access a screen--when the app is offline. I assume there are no standardized ways to implement this w/ Auth or a db?

Of course, I'll be reviewing this constraint with our client next time we meet w/ them.

**Comment by tujson** [comment]
Probably best if we take this offline.

What I've seen for offline auth is storing and validating auth token. When the user wants to publish data, have them re-authenticate (hence, new token) to make sure it's actually them and not... an old version of them.
