### ISSUE TITLE
Test app thoroughly before test deploy

### ISSUE THREAD

**Issue by michaelyfan** [dscgt/recycling_checkin#28]
re: 9 sept meeting

aiming to deploy recycling checkin as test app later in the month! we should be testing it more thoroughly first though.

**Comment by michaelyfan** [comment]
Integration testing with a live Firebase instance is not possible until #29, unless we want to risk testing on prod resources

**Comment by tujson** [comment]
The pubspec.yaml seems to indicate you're only using Cloud Firestore. Could you maybe mock it?
There's also this: https://github.com/atn832/cloud_firestore_mocks
Related issue: https://github.com/FirebaseExtended/flutterfire/issues/896
