### ISSUE TITLE
Sync with Cloud Firestore

### ISSUE THREAD

**Issue by michaelyfan** [dscgt/recycling_checkin#4]
re: discussion with Jack Wolfard. While this app will rely on local storage, Cloud Firestore will be used as a backup. The app should backup when possible*, and should restore from backup only at the user's discretion. 

*research best times to backup -- every day at same time? every minute? every hour? etc.

**Comment by tujson** [comment]
Cloud Firestore has offline capabilities enabled by default. It'll also auto sync when connected to the internet.
